version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chess_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess_game
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
